# 交通灯 开关选择编辑版 约束文件 (EGO1, 无子板)
set_property PACKAGE_PIN P17 [get_ports clk]

# 拨码开关：SW0 进入编辑  SW1 南北直行 SW2 东西直行 SW3 东西转弯 SW4 南北转弯
# 灯测试模式(按S2进入)下 SW0~SW7 直接控制 8 个 LED
set_property PACKAGE_PIN P5 [get_ports {sw[0]}]
set_property PACKAGE_PIN P4 [get_ports {sw[1]}]
set_property PACKAGE_PIN P3 [get_ports {sw[2]}]
set_property PACKAGE_PIN P2 [get_ports {sw[3]}]
set_property PACKAGE_PIN R2 [get_ports {sw[4]}]
set_property PACKAGE_PIN M4 [get_ports {sw[5]}]
set_property PACKAGE_PIN N4 [get_ports {sw[6]}]
set_property PACKAGE_PIN R1 [get_ports {sw[7]}]

# 按键：S3(V1)加一  S0(R11)减一  S2(R15)按住显示9999
set_property PACKAGE_PIN V1  [get_ports key_inc]
set_property PACKAGE_PIN R11 [get_ports key_dec]
set_property PACKAGE_PIN R15 [get_ports s2]

# 数码管位选
set_property PACKAGE_PIN G2 [get_ports {sm_wei[0]}]
set_property PACKAGE_PIN C2 [get_ports {sm_wei[1]}]
set_property PACKAGE_PIN C1 [get_ports {sm_wei[2]}]
set_property PACKAGE_PIN H1 [get_ports {sm_wei[3]}]
# 数码管段选
set_property PACKAGE_PIN B4 [get_ports {sm_duan[0]}]
set_property PACKAGE_PIN A4 [get_ports {sm_duan[1]}]
set_property PACKAGE_PIN A3 [get_ports {sm_duan[2]}]
set_property PACKAGE_PIN B1 [get_ports {sm_duan[3]}]
set_property PACKAGE_PIN A1 [get_ports {sm_duan[4]}]
set_property PACKAGE_PIN B3 [get_ports {sm_duan[5]}]
set_property PACKAGE_PIN B2 [get_ports {sm_duan[6]}]
set_property PACKAGE_PIN D5 [get_ports {sm_duan[7]}]

# 交通灯 LED 面板 = D2 那排 8 个绿色 LED
# [0]南北红 [1]南北黄 [2]南北绿 [3]东西红 [4]东西黄 [5]东西绿 [6]南北左转 [7]东西左转
set_property PACKAGE_PIN K2 [get_ports {led_panel[0]}]
set_property PACKAGE_PIN J2 [get_ports {led_panel[1]}]
set_property PACKAGE_PIN J3 [get_ports {led_panel[2]}]
set_property PACKAGE_PIN H4 [get_ports {led_panel[3]}]
set_property PACKAGE_PIN J4 [get_ports {led_panel[4]}]
set_property PACKAGE_PIN G3 [get_ports {led_panel[5]}]
set_property PACKAGE_PIN G4 [get_ports {led_panel[6]}]
set_property PACKAGE_PIN F6 [get_ports {led_panel[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports key_inc]
set_property IOSTANDARD LVCMOS33 [get_ports key_dec]
set_property IOSTANDARD LVCMOS33 [get_ports s2]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_wei[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_wei[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_wei[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_wei[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_duan[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_duan[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_duan[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_duan[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_duan[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_duan[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_duan[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_duan[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_panel[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_panel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_panel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_panel[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_panel[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_panel[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_panel[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_panel[7]}]
