# 交通灯 编辑模式版 约束文件 (EGO1, 无子板)
set_property PACKAGE_PIN P17 [get_ports clk]
# S2(R15)进出编辑  S1(R17)南北+  S0(R11)南北-  S4(U4)东西+  S3(V1)东西-
set_property PACKAGE_PIN R15 [get_ports s2]
set_property PACKAGE_PIN R17 [get_ports ns_inc]
set_property PACKAGE_PIN R11 [get_ports ns_dec]
set_property PACKAGE_PIN U4  [get_ports we_inc]
set_property PACKAGE_PIN V1  [get_ports we_dec]

# 数码管位选
set_property PACKAGE_PIN G2 [get_ports {sm_wei[0]}]
set_property PACKAGE_PIN C2 [get_ports {sm_wei[1]}]
set_property PACKAGE_PIN C1 [get_ports {sm_wei[2]}]
set_property PACKAGE_PIN H1 [get_ports {sm_wei[3]}]
# 数码管段选
set_property PACKAGE_PIN B4 [get_ports {sm_duan[0]}]
set_property PACKAGE_PIN A4 [get_ports {sm_duan[1]}]
set_property PACKAGE_PIN A3 [get_ports {sm_duan[2]}]
set_property PACKAGE_PIN B1 [get_ports {sm_duan[3]}]
set_property PACKAGE_PIN A1 [get_ports {sm_duan[4]}]
set_property PACKAGE_PIN B3 [get_ports {sm_duan[5]}]
set_property PACKAGE_PIN B2 [get_ports {sm_duan[6]}]
set_property PACKAGE_PIN D5 [get_ports {sm_duan[7]}]

# 交通灯 LED 面板 = D2 那排 8 个绿色 LED
# [0]南北红 [1]南北黄 [2]南北绿 [3]东西红 [4]东西黄 [5]东西绿 [6]南北左转 [7]东西左转
set_property PACKAGE_PIN K2 [get_ports {led_panel[0]}]
set_property PACKAGE_PIN J2 [get_ports {led_panel[1]}]
set_property PACKAGE_PIN J3 [get_ports {led_panel[2]}]
set_property PACKAGE_PIN H4 [get_ports {led_panel[3]}]
set_property PACKAGE_PIN J4 [get_ports {led_panel[4]}]
set_property PACKAGE_PIN G3 [get_ports {led_panel[5]}]
set_property PACKAGE_PIN G4 [get_ports {led_panel[6]}]
set_property PACKAGE_PIN F6 [get_ports {led_panel[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports s2]
set_property IOSTANDARD LVCMOS33 [get_ports ns_inc]
set_property IOSTANDARD LVCMOS33 [get_ports ns_dec]
set_property IOSTANDARD LVCMOS33 [get_ports we_inc]
set_property IOSTANDARD LVCMOS33 [get_ports we_dec]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_wei[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_wei[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_wei[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_wei[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_duan[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_duan[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_duan[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_duan[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_duan[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_duan[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_duan[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sm_duan[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_panel[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_panel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_panel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_panel[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_panel[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_panel[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_panel[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_panel[7]}]
